---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: Docling ServingRuntime for KServe
    opendatahub.io/template-name: docling-runtime
    openshift.io/display-name: docling
  name: docling
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  containers:
    - image: 'quay.io/rh-aiservices-bu/docling-server:cuda-0.0.7'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: Docling
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: docling
    serving.kserve.io/deploymentMode: RawDeployment
  name: docling
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: Docling
      name: ''
      resources:
        limits:
          cpu: '6'
          memory: 24Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '4'
          memory: 8Gi
          nvidia.com/gpu: '1'
      env:
        - name: UVICORN_WORKERS
          value: '4'
      runtime: docling
      storage:
        key: aws-connection-models
        path: dummy/
    tolerations:
      - key: nvidia.com/gpu
        operator: Equal
        value: Tesla-T4-SHARED
        effect: NoSchedule