---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deepsparse-app
  labels:
    component: deepsparse-text-generation
    purpose: deepsparse-app
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: llm-servers/deepsparse/gitops
    repoURL: >-
      https://github.com/rh-aiservices-bu/llm-on-openshift
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true