apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-machine-api

resources:
  # wave 0
  - rbac.yaml
  - configure-autoscaler.yaml
  - cluster-autoscaler.yaml

configMapGenerator:
  - name: configure-autoscaler-files
    files:
      - files/entrypoint.sh
      - files/machineset.yaml
      - files/machine-autoscaler.yaml
