apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  # prehook
  - validate-noobaa.yaml
  # wave 0 deploy
  - objectbucketclaim.yaml
  # posthook
  - create-data-connection.yaml
