apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # prehook
  - validate-install.yaml
  # wave 0 deploy
  - dsc.yaml
  #removed while testing on a non GPU cluster
  #- accelerator-profile.yaml