---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: enable-odf-console-plugin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enable-odf-console-plugin
rules:
  - apiGroups:
      - operator.openshift.io
    resources:
      - consoles
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: enable-odf-console-plugin
subjects:
- kind: ServiceAccount
  name: enable-odf-console-plugin
  namespace: openshift-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enable-odf-console-plugin
---
apiVersion: batch/v1
kind: Job
metadata:
  name: enable-odf-console-plugin
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: enable-plugin
          image: 'image-registry.openshift-image-registry.svc:5000/openshift/tools:latest'
          env:
            - name: PLUGIN_NAME
              value: odf-console
          command:
            - /bin/sh
            - -c
            - |
              echo "Attempting to enable ${PLUGIN_NAME} plugin"
              echo ""
            
              # Create the plugins section on the object if it doesn't exist
              if [ -z "$(oc get consoles.operator.openshift.io cluster -o=jsonpath='{.spec.plugins}')" ]; then
                echo "Creating plugins object"
                oc patch consoles.operator.openshift.io cluster --patch '{ "spec": { "plugins": [] } }' --type=merge
              fi
            
              INSTALLED_PLUGINS=$(oc get consoles.operator.openshift.io cluster -o=jsonpath='{.spec.plugins}')
              echo "Current plugins:"
              echo "${INSTALLED_PLUGINS}"
            
              if [[ "${INSTALLED_PLUGINS}" == *"${PLUGIN_NAME}"* ]]; then
                  echo "${PLUGIN_NAME} is already enabled"
              else
                  echo "Enabling plugin: ${PLUGIN_NAME}"
                  oc patch consoles.operator.openshift.io cluster --type=json --patch '[{"op": "add", "path": "/spec/plugins/-", "value": "'"${PLUGIN_NAME}"'"}]'
              fi
            
              sleep 6
              oc get consoles.operator.openshift.io cluster -o=jsonpath='{.spec.plugins}'
      serviceAccountName: enable-odf-console-plugin
