kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-creator: admin
    opendatahub.io/notebook-image-desc: 'quay.io/rh-aiservices-bu/odh-tec:1.2.1'
    opendatahub.io/notebook-image-name: 'CUSTOM: ODH-TEC'
    opendatahub.io/notebook-image-order: "04"
    opendatahub.io/notebook-image-url: 'quay.io/rh-aiservices-bu/odh-tec:1.2.1'
    opendatahub.io/recommended-accelerators: "[]"
    argocd.argoproj.io/sync-wave: "1"
  name: is-odh-tec
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/created-by: byon
    opendatahub.io/dashboard: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "1.2.1"
      annotations:
        opendatahub.io/notebook-python-dependencies: '[]'
        opendatahub.io/notebook-software: '[]'
        openshift.io/imported-from: 'quay.io/rh-aiservices-bu/odh-tec:1.2.1'
      from:
        kind: DockerImage
        name: >-
          quay.io/rh-aiservices-bu/odh-tec:1.2.1
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
