kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-creator: admin
    opendatahub.io/notebook-image-desc: >-
      Jupyter image with all the libraries needed and a notebook for running InstructLab SDG on OpenShift AI.
    opendatahub.io/notebook-image-name: "CUSTOM: InstructLab SDG"
    opendatahub.io/notebook-image-order: "03"
    opendatahub.io/notebook-image-url: >-
      https://github.com/rh-aiservices-bu/sdg-notebook
    opendatahub.io/recommended-accelerators: "[]"
    argocd.argoproj.io/sync-wave: "1"
  name: workbench-ilab-sdg
  namespace: redhat-ods-applications
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/notebook-image: "true"
    app.kubernetes.io/created-by: byon
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "latest"
      annotations:
        openshift.io/imported-from: quay.io/rh-aiservices-bu/sdg-notebook:latest
      from:
        kind: DockerImage
        name: >-
          quay.io/rh-aiservices-bu/sdg-notebook:latest
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
