apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

resources:
  # wave 0 define namespace
  - namespace.yaml
  # wave 1 install operator
  - operator-group.yaml
  - subscription.yaml
